### PR TITLE
USGS Challenge Details 

### PR DESCRIPTION
**Pull request by jzwart**
I'm going to merge this in so that other PRs are more manageable and easier to see changes. 

Major changes from this PR are: 
- removing files and themes from neon4cast that will not be used in usgsrc4cast
- changing names on configuration files and elsewhere to be specific for usgs river chl challenge 
- adding in USGS site metadata and targets pipeline for pulling site observations

### CODE REVIEW

**Comment by jzwart** [comment]
@rqthomas  could you [add secrets to this repo](https://github.com/eco4cast/usgsrc4cast-ci/settings/secrets/actions) to be used for access to GitHub, AWS, OSN, etc...? You'd probably know what is necessary, but so far I see the following secrets that are needed for GitHub Actions: 

- [ ] GITHUB_TOKEN
- [ ] PAT (which I suspect might be the same as GITHUB_TOKEN above)
- [ ] AWS_ACCESS_KEY_SUBMISSIONS 
- [ ] AWS_SECRET_ACCESS_KEY_SUBMISSIONS 
- [ ] AWS_ACCESS_KEY_ID
- [ ] AWS_SECRET_ACCESS_KEY 
- [ ] OSN_KEY
- [ ] OSN_SECRET 
- [ ] DOCKERHUB_USERNAME
- [ ] DOCKERHUB_TOKEN

Not sure what the multiple AWS keys are for - I assume there are different buckets for submissions, scoring, etc...

**Comment by rqthomas** [comment]
I added the relevant github secrets to the repo

**Comment by jzwart** [comment]
Thanks @rqthomas !

**Comment by jzwart** [comment]
[Targets file generation is working](https://github.com/eco4cast/usgsrc4cast-ci/actions/runs/7281586525), just not pushing to anywhere yet.

**Pull request merged**
